name: streak_meister
description: "StreakMaster - an app to track goal progress"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.4
  data_repository:
    path: packages/data_repository
  # TODO: remove once issue #5
  data_layer:
    path: packages/data_layer
  local_data_layer:
    path: packages/local_data_layer
  # TODO: remove once concrete UserLayer implementation is ready
  user_layer:
    path: packages/user_layer
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

fonts:
  - family: NotoEmoji
    fonts:
      - asset: assets/fonts/NotoColorEmoji-Regular.ttf