name: data_layer
description: >-
  Abstract definition of a library that stores data (goals, milestones, daily
  check-ins and streak information) for StreakMeister app. Packages implementing
  this should subclass `DataLayer` class.
publish_to: none
version: 0.0.1

environment:
  sdk: '^3.6.0'

dependencies:
  equatable: ^2.0.7
  meta: ^1.16.0

dev_dependencies:
  test: '>=1.15.0 <2.0.0'